/*  -------------------------------------------------- **/
/*  Generated by Enterprise Architect Version 8.0.858**/
/*  Created On : 星期六, 21 二月, 2015 **/
/*  DBMS       : MySql **/
/*  -------------------------------------------------- **/

USE stock
;

DROP TABLE if exists T_SAC_MENU;
CREATE TABLE T_SAC_MENU
(
	menu_id BIGINT NOT NULL,
	menu_parent_id BIGINT DEFAULT -1,
	menu_name NVARCHAR(128),
	menu_icon NVARCHAR(24),	
	menu_desc NVARCHAR(256),
	action_address NVARCHAR(128),
	action_type INTEGER default -1,
	menu_status INTEGER DEFAULT 1,
	PRIMARY KEY (menu_id)
) COMMENT='菜单表'
;

DROP TABLE if exists T_SAC_ROLE;
CREATE TABLE T_SAC_ROLE
(
	role_id BIGINT NOT NULL AUTO_INCREMENT,
	role_type INTEGER default -1,
	description NVARCHAR(256),
	PRIMARY KEY(role_id)
) COMMENT='角色表'
;


DROP TABLE if exists T_SAC_USER_ROLE;
CREATE TABLE T_SAC_USER_ROLE
(
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL
) COMMENT='用户角色表'
;

DROP TABLE if exists T_SAC_ROLE_MENU;
CREATE TABLE T_SAC_ROLE_MENU
(
	role_id BIGINT NOT NULL,
	menu_id BIGINT NOT NULL
) COMMENT='角色菜单表'
;

DROP TABLE if exists T_SAC_USER;
CREATE TABLE T_SAC_USER
(
	user_id BIGINT NOT NULL AUTO_INCREMENT,
	user_name NVARCHAR(128),
	user_nick NVARCHAR(128),
	user_password NVARCHAR(128),
	phone NVARCHAR(32),
	email NVARCHAR(32),
	qq NVARCHAR(32),
	weixin NVARCHAR(32),
	create_time DATETIME NOT NULL COMMENT '创建时间',
	update_time DATETIME NOT NULL COMMENT '更新时间',
	PRIMARY KEY(user_id)
) COMMENT='用户表'
;


DROP TABLE if exists T_SAC_USER_LOGIN;
CREATE TABLE T_SAC_USER_LOGIN
(
	user_id BIGINT NOT NULL,
	user_stat INTEGER default -1,
	user_session_id NVARCHAR(48),
	user_login_fail_count INTEGER default 0,
	user_lock_flag INTEGER default 0,	
	login_time DATETIME NOT NULL COMMENT '创建时间',
	PRIMARY KEY(user_id)
) COMMENT='用户状态表'
;


